language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install coveralls
script: coverage run py.test
after_success:
    coveralls
